### PR TITLE
build: syncing package.json to match Swarm and adding podfile

### PR DESCRIPTION
**Pull request by nwind21**
I did a test where I reverted my changes it reproduced the failure. For good measure, I made all the modules in sync especially the react and react-native versions and matched the metro babel preset to match Swarm as well.

Not sure if this change will affect Android though, may want to check.

### CODE REVIEW

**Comment by thearad** [comment]
The package.json changes mentioned shouldnt affect android, in fact I needed to update rn to Swarm's version in order to get the gradle build to succeed. Feel free to add the package.json changes to this pr.

**Comment by thearad** [comment]
Currently I'm getting:
```
Error: ENOENT: no such file or directory, lstat '/Users/dev/Desktop/swarm_workspace_ar/react-native-cam/react-native-camera/examples/basic/ios/build/ModuleCache.noindex/2UDD6PDI9RTSC/CoreImage-2L8M44C0CYIPM.pcm-9581b5be'
Process terminated. Press <enter> to close the window
```
Do I need to run pod install after npm I? What's weird is the build succeeds but the metro bundler throws the above err. I'll try putting in the updated versions into package.json and see if that helps.

**Comment by thearad** [comment]
When running with updated package.json I'm getting:
```
The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/RNCameraExample.app/RNCameraExample normal x86_64
(1 failure)
```

**Comment by thearad** [comment]
Just got this working, updated to Xcode 10 cmd line & ran pod install (which I had forgotten to run before). For some reason I was getting a babel/runtime haste map error for the react-native-camera package, ran npm install in the root package directory and it worked after that.

Package.json changes and App.js import change ('react-native-camera' -> '@divx/react-native-camera') should be added to pr.

**Comment by nwind21** [comment]
Changes were committed, must've missed this in the prior commit.

**Pull request merged**
